<cfquery name="get_current_status" datasource="MySQL">
select host_fam_approved, arearepid from smg_students
where studentid = #cookie.review_student#
</cfquery>
<Cfquery name="get_rep_info" datasource="mysql">
select email, firstname
from smg_users
where userid = #get_current_status.arearepid#
</Cfquery>
<Cfquery name="student_info" datasource="mysql">
select firstname, familylastname
from smg_students
where studentid = #cookie.review_student#
</Cfquery>
<cfset currentstatus = 99>



<cfif client.usertype gte #get_Current_status.host_fam_approved#>
	<cfquery name="update_report" datasource="MySQL">
	update smg_students
	set host_fam_approved = #currentstatus#
	where studentid =#cookie.review_student#
	</cfquery>
</cfif>
<cfoutput>
<cfmail to=#get_rep_info.email# from=FROM="""SMG Support"" <support@student-management.com>" subject="Rejected Placement Information Sheet">
#get_Rep_info.firstname#,

The Placement Information for #student_info.firstname# #student_info.familylastname# was rejected. 

Please visit #CLIENT.exits_url# to:
-view why it was rejected
-make the necessary changes


#client.name#
--
This email was generated by the system.  Questions about the reasons it was rejected should be directed to the sender.  
Technical issues should be directed to support@student-management.com, include the ID:s#cookie.review_student#h#cookie.review_host#ar#get_current_status.arearepid#
</cfmail>
</cfoutput>

	<cfcookie name="review_host"  value=1 expires="now">
	<cfcookie name="review_student"  value=1 expires="now">
<cflocation url="../index.cfm?curdoc=pending_hosts">