<style type="text/css">
.remarks {
	font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
	font-size: 11px;
	font-style: italic;
	color: #000;
	background-color: #FC9;
	text-align: center;
	width: 200px;
	margin-right: -20px;
	margin-left: 0px;
	float: right;
	font-weight: bold;
	padding-top: 10px;
	padding-right: 20px;
	padding-bottom: 10px;
	padding-left: 20px;
	margin-top: 2px;
}
</style> 
 
 <div class="HFtopPic"><img src="images/hostFamily/benefits_Header.png" width="700" height="220" Border="0" /><img src="images/hostFamily/HF_bar.jpg" width="700" height="13" />

     <!--end subPages--> </div>
     
      <div class="HFsidebarRW">
      
      <img src="images/hostFamily/benefits_pic.png" width="200"/>
      
        <div class="HF_boxW"></div>
<div class="HF_boxOrg">
    <h1 class="HFheader"><img src="images/hostFamily/HF_arrow.png" width="18" height="15" alt="arrow" />From the CSIET 2007 survey of host families</h1>

&#187; Host family learning experience provided benefits not only culturally but also socially.<br /><br />
&#187; Host families gained a new perspective on its own country and culture from their students.<br /><br />
&#187; Student hosting was especially beneficial in terns of enhancing its own family setting, such as making new extended family, and having more interaction and mutual respect as a family of companies.<br /><br />
&#187; Host families received cultural experiences due to interaction and exposure to other cultures and customs.<br /><br /><br />
<div class="remarks">When American families host an INTERNATIONAL EXCHANGE STUDENT, they are embarking on an unforgettable cultural adventure that will last a lifetime.</div>
      <!--HF_boxOrg--></div><br />
      
      <!--end HFsidebarR--></div>
        <div class="HFsidebarLW">
        <div class="HFpicL"></div>
     <br />   <br />
     <h1 class="HFheader"><img src="images/hostFamily/HF_arrow.png" width="18" height="15" alt="arrow" />Every Family Member will have a Unique Experience</h1>
          <ul><li>You and your family will be exploring your differences, discovering surprising similarities, and teaching your new son or daughter about your American values and beliefs.</li>
<li>Your Family will be seeing the United States through a new pair of eyes of an inquisitive teen, and rediscovering the simple things that we often take for granted a baseball or football game, a community picnic, even window-shopping at the mall!</li>
<li>Your children will enjoy sharing school, community and family information with an &quot;adopted&quot; brother or sister.</li>
<li>Each member of your family will learn a lot about themselves as they share their lives with another young person.</li></ul>
          <br /><br />
          
      <div class="HFpicR"></div>  
<div class="HFgradient">
  <br />
<h1 class="HFheader"><img src="images/hostFamily/HF_arrow.png" width="18" height="15" alt="arrow" />What Benefits a Family Receives</h1>
  <ol><strong>By Enriching, Educating, and Enlightening</strong> your family, you will be gaining new insights and a renewed appreciation for different cultures and a step toward a safer world for your children and grandchildren.</ol>
      <ol>
        <strong>A New Understanding</strong> as you see the world through the rose colored eyes of your new son or daughter.
  </ol>
      <ol>
        <strong>A New View</strong> brings a renewed interest and pride in your ancestry generated by the excitement brought to you by your new family member.
  </ol>
      <ol>
        <strong>Interest in Language</strong> will inspire your children that learning a new language is easy, fun and careers in an International Business, which once seemed distance, now becomes real and possible in the global world of today.
    </ol>
     <ol> 
       <strong>Lifelong Friends</strong> are realized as your new son/daughter say goodbye. Your children now have a new brother or sister across the world. Your exchange student will give you Love, Respect and Pride just as your children do.
   </ol>
     <ol> 
       <strong>Confidence and an Open Mindedness</strong> will become more comfortable as your children see their new sister or brother adapt and thrive in a totally foreign situation. Learning how similar we all are helps us to open our minds and hearts toward the new and different.
   </ol>
     <ol> 
       <strong>Allows Family</strong> members to visit their new family member experience their culture and customs first hand.
  </ol>
      <ol>
        <strong>Be a Diplomat </strong>by sharing the true American with the world and making the world a safer place for your children and grandchildren. Exchange is America's Number 1 Ambassador for America.
      </ol>
   <br /><br />
</div><br />
        
          
        <!--end HFsidebarL--></div>
<div class="clearfix">&nbsp;</div>
<div class="HFtopPic"><img src="images/hostFamily/HF_bar.jpg" width="700" height="13" /></div>
<div class="clearfix">&nbsp;</div>