
	<link rel="stylesheet" type="text/css" href="css/mainSlide.css" />
	<script type="text/javascript" src="js/jquery.js"></script>
	<!-- End WOWSlider.com HEAD section -->

	<!-- Start WOWSlider.com BODY section -->
	<div id="wowslider-container1">
	<div class="ws_images"><ul>
    <li><img src="images/MainSlides/studentexchange.jpg" alt="ISE students come from all over the world and are excited about their upcoming exchange program in the United States. Will you be the loving host family that opens the door to the world for an exchange student?" title="Meet our Students" id="wows1_0"/></li>
<li><a href="become-a-host-family.cfm"><img src="images/MainSlides/hostexchangestudent.jpg" alt="Hosting a foreign exchange student is a life changing experience that brings the world closer together. See the world through the eyes of a foreign exchange student and exchange the world! " title="Be a Host Family" id="wows1_1"/></a></li>
<li><a href="meet-our-students.cfm"><img src="images/MainSlides/meetexchangestudents.jpg" alt="MeetExchangeStudents" title="MeetExchangeStudents" id="wows1_2"/></a></li>
<li><a href="study-abroad-outbound.cfm"><img src="images/MainSlides/studyabroad.jpg" alt="American students are invited to go outbound to learn and study in different countries. ISE offers many different types of individualized programs to fit your personal needs." title="Travel Abroad" id="wows1_3"/></a></li>
<li><a href="https://trips.exitsapplication.com" target="_blank"><img src="images/MainSlides/studenttrips.jpg" alt="International Student Exchange offers many trips for our students throughout the school year." title="student Trips" id="wows1_4"/></a><</li>
<li><a href="student-project-help.cfm"><img src="images/MainSlides//projecthelp.jpg" alt="ProjectHelp" title="ProjectHelp" id="wows1_5"/></a></li>
</ul></div>
<div class="ws_bullets"><div>
<a href="index.cfm" title="studentExchange">1</a>
<a href="become-a-host-family.cfm" title="HostExchangeStudent">2</a>
<a href="meet-our-students.cfm" title="MeetExchangeStudents">3</a>
<a href="study-abroad-outbound.cfm" title="studyAbroad">4</a>
<a href="#" title="studentTrips">5</a>
<a href="student-project-help.cfm" title="ProjectHelp">6</a>


</div></div>
<!-- Generated by WOWSlider.com v4.7 -->
	<div class="ws_shadow"></div>
	</div>
	<script type="text/javascript" src="js/wowslider.js"></script>
	<script type="text/javascript" src="js/script.js"></script>
	<!-- End WOWSlider.com BODY section -->
