<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<title>Insert Help Desk Ticket</title>
</head>

<body>

<cftry>

<cfoutput>

<cftransaction action="begin" isolation="serializable">

	<!--- GET CURRENT USER --->
	<cfinclude template="../querys/get_user.cfm">

	<cfif form.title EQ '' OR form.category EQ 0 OR form.section EQ 0 OR form.text EQ ''>
		<table  bgcolor="FFFFFF" bordercolor="CCCCCC" border="1" height="100%" width="100%">
			<tr bordercolor="FFFFFF">
				<td>
					<table width=100% cellpadding=0 cellspacing=0 border=0 align="center" height="25" bgcolor="E4E4E4">
					<tr bgcolor="E4E4E4">
						<td class="title1">&nbsp; &nbsp; Help Desk - Add Ticket</td>
					</tr>
					</table><br>
					<table border=0 cellpadding=4 cellspacing=0 class="section" align="center" width=90%>
						<tr><th class="style1">EXTRA - Input Error</th></tr>
						<tr><td class="style1">Title, description, category and section are required fields. Please make sure to fill all of them out in order to submit a ticket.</td></tr>
						<tr><td align="center" class="style1"><input type="image" value="back" src="../pics/goback.gif" onClick="javascript:history.back()"></td></tr>		
					</table><br />
				</td>
			</tr>
		</table>		
		<cfabort>	
	</cfif>

	<cfquery name="assigned_to" datasource="MySql">
		SELECT sectionid,  sectionname,  assignedid,  
			userid, firstname, lastname, email 
		FROM smg_help_desk_section
		LEFT JOIN smg_users ON assignedid = userid
		WHERE sectionid = '#form.section#'
	</cfquery>

	<cfset newtext = #Replace(form.text,"#chr(10)#","<br>","all")#>

	<cfquery name="insert_help_desk" datasource="MySql">
		INSERT INTO smg_help_desk
			(companyid, title, category, section, priority, text, status, submitid, assignid, date)
		VALUES ('#client..companyid#', '#form.title#','#form.category#', '#form.section#',
				<cfif form.category EQ 'suggestion' OR form.category EQ 'question'>'low',</cfif>
				<cfif form.category EQ 'error' OR form.category EQ 'request'>'medium',</cfif>
				<cfif form.category EQ 'problem'>'high',</cfif>
				<cfqueryparam value="#newtext#" cfsqltype="cf_sql_longvarchar">, 'initial','#client..userid#', '#assigned_to.assignedid#', #CreateODBCDateTime(now())#)
	</cfquery>

	<cfquery name="get_ticket" datasource="mysql">
		SELECT Max(helpdeskid) as helpdeskid
		FROM smg_help_desk
	</cfquery>

	<cfset folder = ''>
	<!--- SET FOLDER TO INCLUDE LINK --->
	<cfif client..companyid EQ 7>
		<cfset folder = 'trainee'>
	<cfelseif client..companyid EQ 8>
		<cfset folder = 'wat'>
	<cfelseif client..companyid EQ 9>
		<cfset folder = 'h2b'>
	</cfif>

	<cfquery name="insert_link" datasource="MySQL">
		INSERT INTO smg_links 
			(link)
		VALUES 
			('https://www.student-management.com/extra/internal/#folder#/index.cfm?curdoc=helpdesk/helpdesk_view&helpdeskid=#get_ticket.helpdeskid#')
	</cfquery>

	<cfquery name="get_link_id" datasource="MySQL">
		SELECT Max(id) as linkid
		FROM smg_links
	</cfquery>

	<!--- EMAIL TO USER --->
	<cfif get_user.email NEQ ''>
		<cfmail from="helpdesk@student-management.com" to="#get_user.email#" subject="EXTRA Help Desk - Ticket ###get_ticket.helpdeskid# - New Message Submitted">
Dear #get_user.firstname# #get_user.lastname#,

On #dateformat (now(), "dd/mm/yyyy")# at #timeformat(now(), 'h:mm:ss tt')# you submitted a request for service in the help desk 
and the EXTRA Technical Support Team will be reviewing it soon.

Ticket ## #get_ticket.helpdeskid#.

Please click on the link to check the status, review the item, or add additional information. 

http://www.student-management.com/extra/?link=#get_link_id.linkid#
			
*Authentication maybe required if you are not currently logged on to the Student Management website.*

You will receive an e-mail when we update/answer your ticket.

Please DO NOT reply to this email message.  All comments on this item need to be submitted through the helpdesk system.
If you would like to post a message, please visit the link above and enter your comment in the area labled: 'Enter New Message'

SMG Technical Support
===================================================
This is confidential information automatically
generated by SMG.  If you have any concerns please
contact support@student-management.com immediately.
===================================================
		</cfmail>
	</cfif>
	
	<!--- EMAIL TO SUPPORT --->
	<cfif assigned_to.email NEQ ''>
		<cfmail from="helpdesk@student-management.com" to="#assigned_to.email#, wayne@iseusa.com" subject="EXTRA Help Desk - Ticket ###get_ticket.helpdeskid# - New Message Submitted">
Dear #assigned_to.firstname# #assigned_to.lastname#,

A new request of service has been submitted to you.
Item Link: http://www.student-management.com/extra/?link=#get_link_id.linkid#

Ticket ## #get_ticket.helpdeskid#.

Title: #form.title#
Category: #form.category#

Text: #form.text#

Submitted on: #dateformat (now(), "dd/mm/yyyy")# by #get_user.firstname# #get_user.lastname#.
		</cfmail>
	<cfelse>
		<cfmail from="helpdesk@student-management.com" to="support@student-management.com" subject="EXTRA Help Desk - Ticket ###get_ticket.helpdeskid# - New Message Submitted">
Support,

A new request of service has been submitted to you.
Item Link: http://www.student-management.com/extra/?link=#get_link_id.linkid#

Ticket ## #get_ticket.helpdeskid#.

Title: #form.title#
Category: #form.category#

Text: #form.text#

Submitted on: #dateformat (now(), "dd/mm/yyyy")# by #get_user.firstname# #get_user.lastname#.
		</cfmail>
	</cfif>

	<html>
	<head>
	<script language="JavaScript">
	<!-- 
	alert("Your ticket has successfully been sent, Thank You.");
	<!-- 
	location.replace("?curdoc=helpdesk/helpdesk_menu");
	-->
	</script>
	</head>
	</html> 

</cftransaction>

</cfoutput>	

<cfcatch type="any">
	<cfinclude template="../error_message.cfm">
</cfcatch>

</cftry>

</body>
</html>