<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<title>Insert Help Desk Comment</title>
</head>

<body>

<cftry>

<cfoutput>

<cftransaction action="begin" isolation="serializable">

	<cfquery name="get_help_desk" datasource="MySQL">
		SELECT *
		FROM smg_help_desk
		WHERE helpdeskid = <cfqueryparam value="#form.helpdeskid#" cfsqltype="cf_sql_integer">
	</cfquery>
	
	<cfquery name="get_user_submitted" datasource="MySql">
		SELECT email, firstname, lastname
		FROM smg_users
		WHERE userid = '#get_help_desk.submitid#'
	</cfquery>

	<Cfquery name="find_link" datasource="mysql">
		SELECT id
		FROM smg_links
		WHERE link like '%helpdeskid=#form.helpdeskid#%'
	</Cfquery>

	<!--- FORMAT COMMENTS --->
	<cfset newtext = #Replace(form.text,"#chr(10)#","<br>","all")#>

	<!--- ADMIN USERS --->
	<cfif client..usertype EQ 1>
	
		<!--- UPDATE ASSIGNMENT / STATUS / PRIORITY  --->
		<cfquery name="update_help_desk" datasource="MySql"> 
			UPDATE smg_help_desk	
				SET assignid = '#form.assignid#'
					<cfif form.status NEQ 0>, status = '#form.status#' </cfif>
					<cfif form.priority NEQ 0>, priority = '#form.priority#'</cfif>
			WHERE helpdeskid = '#form.helpdeskid#'
		</cfquery>
		
		<!--- ADD NEW COMMENT / MESSAGE --->
		<cfif form.text NEQ ''>
			<cfquery name="insert_help_desk_items" datasource="MySql">
				INSERT INTO smg_help_desk_items
					(helpdeskid, submitid, text, date)
				VALUES
					('#form.helpdeskid#','#client..userid#', <cfqueryparam value="#newtext#" cfsqltype="cf_sql_longvarchar">, #CreateODBCDateTime(now())#)
			</cfquery>
					
			<!--- MESSAGE SENT TO USERS WHEN SMG TECHNICAL ANSWERS A REQUEST --->
			<cfif get_user_submitted.email NEQ ''>
				<cfmail from="helpdesk@student-management.com" to="#get_user_submitted.email#" subject="EXTRA Help Desk - New Comment Submitted - Ticket ###form.helpdeskid#">
					Dear #get_user_submitted.firstname# #get_user_submitted.lastname#,
					
					A new comment has been logged in the help desk  regarding a request of service you created.
					
					Ticket ###form.helpdeskid#
					
					To view the comment and current status please visit http://www.student-management.com/extra/?link=#find_link.id#
						
					*Authentication may be required if you are not logged in.*
						
					Please DO NOT reply to this email message.
					If you would like reply to this message, please visit the help desk and log your comments appropriately.
					
					Sincerely-
					SMG Technical Support
					=================================================
					This is confidential information automatically
					generated by SMG.
					If you have any concerns please immediately contact
					support@student-management.com
					=================================================
				</cfmail>
			</cfif>
		</cfif>		
	
	<!--- REGULAR USERS --->
	<cfelse>
		
		<cfquery name="assigned_to" datasource="MySql">
			SELECT userid, firstname, lastname, email 
			FROM smg_users
			WHERE userid = #get_help_desk.assignid#
		</cfquery>
		
		<cfif form.text NEQ ''>
			<!--- UPDATE STATUS TO INFO --->
			<cfquery name="update_help_desk" datasource="MySql">
				UPDATE smg_help_desk
					SET status = 'initial'
					WHERE helpdeskid = '#form.helpdeskid#'
			</cfquery>

			<!--- ADD NEW COMMENT / MESSAGE --->
			<cfquery name="insert_help_desk_items" datasource="MySql">
				INSERT INTO smg_help_desk_items
					(helpdeskid, submitid, text, date)
				VALUES
					('#form.helpdeskid#','#client..userid#', <cfqueryparam value="#newtext#" cfsqltype="cf_sql_longvarchar">, #CreateODBCDateTime(now())#)
			</cfquery>
		
			<!--- MESSAGE SENT TO USERS WHEN SMG TECHNICAL ANSWERS A REQUEST --->
			<cfif get_user_submitted.email NEQ ''>
				<cfmail from="helpdesk@student-management.com" to="#get_user_submitted.email#" subject="EXTRA Help Desk - New Comment Submitted - Ticket ###form.helpdeskid#">
					Dear #get_user_submitted.firstname# #get_user_submitted.lastname#,
					
					A new comment has been logged in the help desk regarding a request of service you created.
					
					Ticket ###form.helpdeskid#
					
					To view the comment and current status please visit http://www.student-management.com/extra/?link=#find_link.id#
				
					*Authentication may be required if you are not logged in.*
						
					Please DO NOT reply to this email message.
					If you would like reply to this message, please visit the help desk and log your comments appropriately.
					
					Sincerely-
					SMG Technical Support
					=================================================
					This is confidential information automatically
					generated by SMG.
					If you have any concerns please immediately contact
					support@student-management.com
					=================================================
				</cfmail>
			</cfif>
		
		</cfif>		
		
	</cfif>	

	<html>
	<head>
	<script language="JavaScript">
	<!-- 
	alert("This ticket has been updated. Thank You.");
	location.replace("?curdoc=helpdesk/helpdesk_view&helpdeskid=#form.helpdeskid#");
	-->
	</script>
	</head>
	</html> 

</cftransaction>

</cfoutput>

<cfcatch type="any">
	<cfinclude template="../error_message.cfm">
</cfcatch>

</cftry>
 
</body>
</html>